// src/pages/PrivacyPolicy.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import AppShell from '../components/AppShell';
import styles from './PrivacyPolicy.module.css';

const ArrowLeft = (props) => (
    <svg {...props} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/>
    </svg>
);

export default function PrivacyPolicy() {
    return (
        <AppShell>
            <div className={styles.pageContainer}>
                <header className={styles.header}>
                    {/* Fixed: Link explicitly to /dashboard instead of / to avoid broken route */}
                    <Link to="/dashboard" className={styles.backLink}>
                        <ArrowLeft className={styles.iconSmall} /> Back to Dashboard
                    </Link>
                    <h1 className={styles.mainTitle}>Privacy Policy</h1>
                    <p className={styles.lastUpdated}>Last Updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
                </header>

                <div className={styles.contentCard}>
                    <section className={styles.policySection}>
                        <h2>1. Introduction</h2>
                        <p>
                            Welcome to VoiceLab. This platform is an advanced AI-powered web workspace designed as a professional audio processing demonstration. 
                            We are highly committed to protecting your digital footprint and maintaining absolute privacy. This policy 
                            explains how your media data interacts with our active AI systems and backend framework.
                        </p>
                    </section>

                    <section className={styles.policySection}>
                        <h2>2. Information We Process (Zero-Auth Model)</h2>
                        <p>VoiceLab operates on a decentralized, zero-authentication architecture. We do not collect names, emails, or credentials. The tracking parameters are limited strictly to volatile audio assets:</p>
                        <ul>
                            <li><strong>Audio Payloads:</strong> Transient sound tracks and raw binary voice buffers (MP3, WAV) you explicitly upload or record via the HTML5 MediaRecorder API.</li>
                            <li><strong>Generated Analytics Text:</strong> Temporary model output text strings generated by the Whisper Speech-to-Text inference engine.</li>
                            <li><strong>Vocal Emotion Matrices:</strong> Multi-class mathematical score arrays computed dynamically by the tone classification neural engines.</li>
                        </ul>
                    </section>

                    <section className={styles.policySection}>
                        <h2>3. Real-Time Data Handling & Pipeline Usage</h2>
                        <p>Your local media assets are transferred temporarily to our high-performance Python/FastAPI backend services solely to run the target audio operations:</p>
                        <ul>
                            <li>Executing localized Spectral Subtraction for advanced background Noise Reduction.</li>
                            <li>Running volume equalization models for crisp Voice Quality Enhancement.</li>
                            <li>Mapping voice wave frequencies into Mel-Frequency Cepstral Coefficients (MFCCs) for Emotion Detection graphs.</li>
                            <li>Synthesizing typed strings into artificial speech audio packages via Neural TTS.</li>
                        </ul>
                        <p><em>Crucial Note: We maintain a strict policy against commercializing user payloads. Your source audio files, text, and predictions are never sold, exposed, or processed to train public/open-source foundational AI models.</em></p>
                    </section>

                    <section className={styles.policySection}>
                        <h2>4. Automated Garbage Collection & Server Erasure</h2>
                        <p>
                            To maintain runtime efficiency and guarantee local data privacy, VoiceLab enforces an automated server cleanup task framework. 
                            Every asset uploaded, along with its server-generated virtual reference objects and transcripts, is <strong>permanently purged from storage within a maximum runtime lifecycle threshold</strong>. 
                            Since data tracks are stateless, they leave no cached residuals or lingering logs behind.
                        </p>
                    </section>

                    <section className={styles.policySection}>
                        <h2>5. Client-Side & Network Security Safeguards</h2>
                        <p>
                            We employ modern software engineering practices to maximize network security. All data payload transfers hit secure 
                            FastAPI routers encapsulated inside structured multipart/form-data constraints. While local browser operations utilize 
                            sandboxed URL memory pointers (`URL.createObjectURL`), please be aware that no internet transmission protocol is 100% impenetrable, 
                            and user caution regarding sensitive data is always recommended.
                        </p>
                    </section>

                    <section className={styles.policySection}>
                        <h2>6. Workspace Reference</h2>
                        <p>
                            VoiceLab is maintained entirely as an open engineering portfolio project. If you have core structural architecture questions, 
                            API deployment inquiries, or configuration suggestions regarding this system, please reach out directly through the official repository or support channels.
                        </p>
                    </section>
                </div>
            </div>
        </AppShell>
    );
}